name: Dich Video Ra MP4

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Link video YouTube'
        required: true
        type: string

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          pip install yt-dlp openai-whisper requests
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Download
        run: yt-dlp -o input.mp4 "${{ github.event.inputs.video_url }}"

      - name: Process
        run: python translate.py

      - name: Upload MP4
        uses: actions/upload-artifact@v4
        with:
          name: video-da-dich
          path: output_dich.mp4

      - name: Upload SRT
        uses: actions/upload-artifact@v4
        with:
          name: phu-de-srt
          path: subtitle.srt
